/*
Copyright 2015 David R. Pugh

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package models

import akka.actor.ActorRef


sealed trait FillLike {

  val askTradingPartyRef: ActorRef

  val bidTradingPartyRef: ActorRef

  val instrument: AssetLike

  val price: Double

  val quantity: Int
  
}


/** Represents a partial fill generated by some MatchingEngine.
  *
  * @param askTradingPartyRef: ActorRef of the participant submitting the ask order.
  * @param bidTradingPartyRef: ActorRef of the participant submitting the bid order.
  * @param price: Agreed price for the partial fill.
  * @param quantity: Agreed quantity for the partial fill.
  */
case class PartialFill(askTradingPartyRef: ActorRef,
                       bidTradingPartyRef: ActorRef,
                       instrument: AssetLike,
                       price: Double,
                       quantity: Int) extends FillLike {

  require(price > 0, "Price must be strictly positive.")
  require(quantity > 0, "Quantity must be strictly positive.")

  override def toString: String = {
    s",${askTradingPartyRef.path.name},${bidTradingPartyRef.path.name},$getClass,$instrument,$price,$quantity"
  }

}


/** Represents a total fill generated by some MatchingEngine.
  *
  * @param askTradingPartyRef: ActorRef of the trading party submitting the ask order.
  * @param bidTradingPartyRef: ActorRef of the trading party submitting the bid order.
  * @param price: Agreed price for the filled order.
  * @param quantity: Agreed quantity for the filled order.
  */
case class TotalFill(askTradingPartyRef: ActorRef,
                     bidTradingPartyRef: ActorRef,
                     instrument: AssetLike,
                     price: Double,
                     quantity: Int) extends FillLike {

  require(price > 0, "Price must be strictly positive.")
  require(quantity > 0, "Quantity must be strictly positive.")

  override def toString: String = {
    s",${askTradingPartyRef.path.name},${bidTradingPartyRef.path.name},$getClass,$instrument,$price,$quantity"
  }

}

